baseurl = "https://maxhenderson.com/"
title = "Max's Blog"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""
googleAnalytics = "UA-142166823-1"

[params]
    author = "Max Henderson"
    description = "Max Henderson's personal website"
    keywords = "blog,personal"
    # info = "(Amateur) technologist, thinker, investor, traveler, and meat popsicle."
    avatarurl = "avatar.jpg"
    favicon_32 = "favicon-32x32.png"
    favicon_16 = "favicon-16x16.png"
 #   footercontent = "Enter a text here."

    dateformat = "Jan 2, 2006"

    hideCredits = true
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

#[[params.social]]
#    name = "Github"
#    icon = "fab fa-github"
#    weight = 1
#    url = "https://github.com/maxwhenderson/"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab"
#    weight = 2
#    url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/maxwhenderson/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/maxhenderson/"
[[params.social]]
    name = "Envelope"
    icon = "fa fa-envelope"
    weight = 5
    url = "mailto:max@maxhenderson.com"


[languages]
    [languages.en]
        languagename = "English"

#         [[languages.en.menu.main]]
#        name = "Home"
#        weight = 1
#        url = "/"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

#        [[languages.en.menu.main]]
#        name = "All Posts"
#        weight = 2
#        url = "/posts/"

#        [[languages.en.menu.main]]
#        name = "Ideas"
#        weight = 3
#        url = "/categories/ideas"

#        [[languages.en.menu.main]]
#        name = "Investing"
#        weight = 4
#        url = "/categories/investing"

#        [[languages.en.menu.main]]
#        name = "Travel Reports"
#        weight = 5
#        url = "/categories/travel-reports"

        [[languages.en.menu.main]]
        name = "Book Notes"
        weight = 6
        url = "/categories/book-notes"

#        [[languages.en.menu.main]]
#        name = "Projects"
#        weight = 4
#        url = "/projects/"

#        [[languages.en.menu.main]]
#        name = "Contact"
#        weight = 5
#        url = "/contact/"